### PR TITLE
retrying otp does not call onboarding

### LINKED ISSUE #14: Register CLI  doesn't complete if OTP is typed incorrectly
**Describe the bug**
Register CLI  doesn't complete if OTP is typed incorrectly

**To Reproduce**
* Run the Register CLI
* Once you receive the OTP, type it in incorrectly
* Then, when prompted, re-enter the OTP correctly
* You will see `Got response: Verified` but that's all - i.e. it stops there, doesn't proceed to the next step (output the cram secret)

**Expected behavior**
It should work the same as when you type the OTP correctly the first time

**Additional context**
(I've replaced the email address I was using with xxx@yyy.zzz.net and changed the name of the atsign that was registered, but otherwise this is the output I got)
```
gkc2019-2:at_client gary$ java -cp "target/client-1.0-SNAPSHOT.jar:target/lib/*" org.atsign.client.cli.Register 'xxx@yyy.zzz.net'
Getting free atsign
Got atsign: @atsign_redacted_for_this_issue
Sending one-time-password to :xxx@yyy.zzz.net
Got response: Sent Successfully
Enter OTP received on: xxx@yyy.zzz.net
w9kw
Validating one-time-password
Got response: Hmm, that code is invalid or expired. Try again?
Incorrect OTP entered. Re-enter the OTP: 
W9KW
Got response: Verified
```

### PR DESCRIPTION
**Pull request by srieteja**
closes https://github.com/atsign-foundation/at_java/issues/14
**- What I did**

- Solved a bug where re-entering otp does not call onboarding
- Handled a case when user exhausts their quota of free atsigns by displaying appropriate message
- Also restructure config yaml and changed the config variables to camelCase

**- How I did it**

- reposition if-else blocks so that the block calling onboarding class is executed every time
- calling API to check if they have exhausted free atsign quota before trying to register it to a users email

**- How to verify it**

- use register CLI and enter incorrect otp and then enter correct otp. Expected behaviour is that onboarding is successfully completed
- try registering a new atsign with an email that has exhausted free atsign limit, the CLI should throw an exception "free atsign limit exhausted"

**- Description for the changelog**

### CODE REVIEW

File: at_client/src/main/java/org/atsign/client/cli/Register.java [hunk 1]
```diff
@@ -24,16 +24,16 @@ public static void main(String[] args) throws Exception {
...
-        String rootDomain = configReader.getProperty("ROOT_DOMAIN");
-        String rootPort = configReader.getProperty("ROOT_PORT");
-        String registrarUrl = configReader.getProperty("REGISTRAR_URL");
-        String apiKey = configReader.getProperty("API_KEY");
-        
-        if (rootDomain == null || rootPort == null || registrarUrl == null || apiKey == null){
+        String rootDomain = configReader.getProperty("rootDomain");
+        String rootPort = configReader.getProperty("rootPort");
+        String registrarUrl = configReader.getProperty("registrarUrl");
+        String apiKey = configReader.getProperty("apiKey");
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/client/cli/Register.java]: This is a breaking change. If the property is null when retrieving with the new name, then try to retrieve using the old name

Consider also adding some structure to the yaml; now's the best time to do this before it gets fossilized by usage

e.g.

root:
  domain: "xxxx"
  port: nnn
registrar:
  url: "https://..."
  apiKey: "xyz456abc123..."

File: at_client/src/main/resources/config.yaml [hunk 2]
```diff
@@ -1,4 +1,4 @@
-API_KEY: "477b-876u-bcez-c42z-6a3d" ##staging api key. please obtain a key to the production registrar api and replace it
-ROOT_DOMAIN: "root.atsign.wtf" ##staging root server. use "root.atsign.org" to use the production root domain
-ROOT_PORT: "64" 
-REGISTRAR_URL: "https://my.atsign.wtf/api/app/v2" ##staging registrar url. please use "https://my.atsign.com/api/app/v2" to use the production registrar api
\ No newline at end of file
+apiKey: "477b-876u-bcez-c42z-6a3d" ##staging api key. please obtain a key to the production registrar api and replace it
+rootDomain: "root.atsign.wtf" ##staging root server. use "root.atsign.org" to use the production root domain
+rootPort: "64" 
+registrarUrl: "https://my.atsign.wtf/api/app/v2" ##staging registrar url. please use "https://my.atsign.com/api/app/v2" to use the production registrar api
```
Comment (gkc) [inline at_client/src/main/resources/config.yaml]: See earlier comment about backwards compatibility / breaking change.

**Review by gkc — CHANGES_REQUESTED** [review]

**Comment by srieteja** [comment]
@gkc the latest commit handles the case when a user exhausts their free atsign limit. The current behaviour is that the CLI prints a log saying "max free atsigns reached". In this case do we want to add functionality where the user could choose from their existing atsigns and the Register CLI would onboard it for them ?

File: at_client/src/main/resources/config.yaml (hunk 2 above)
Comment (srieteja) [reply at_client/src/main/resources/config.yaml]: Restructuring the yaml required me to modify the mechanism/method that reads the yaml file. ConfigReader.getProperty() now accepts different parameters than it did previously. This might not allow retrieving a configuration using the old name.

File: at_client/src/main/java/org/atsign/client/cli/Register.java [hunk 3]
```diff
@@ -24,16 +24,16 @@ public static void main(String[] args) throws Exception {
         String otp;
         String validationResponse;
         String cramSecret;
-        String rootDomain = configReader.getProperty("ROOT_DOMAIN");
-        String rootPort = configReader.getProperty("ROOT_PORT");
-        String registrarUrl = configReader.getProperty("REGISTRAR_URL");
-        String apiKey = configReader.getProperty("API_KEY");
-        
-        if (rootDomain == null || rootPort == null || registrarUrl == null || apiKey == null){
+        String rootDomain = configReader.getProperty("rootServer", "domain");
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/client/cli/Register.java:27]: Add here, for backwards compatibility 
```
if (rootDomain == null) {
  rootDomain = configReader.getProperty("ROOT_DOMAIN");
}
```
and similar for each of the next three config properties

File: at_client/src/main/java/org/atsign/client/util/RegisterUtil.java [hunk 4]
```diff
@@ -108,34 +109,53 @@ public Boolean registerAtsign(String email, AtSign atsign, String registrarUrl,
      * @throws IOException
      * @throws AtException
      */
-    public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey)
+    public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey,
+            boolean confirmation)
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: This is a breaking change. Please make `confirmation` an optional parameter. Customer is directly using this method.

File: at_client/src/main/java/org/atsign/client/util/RegisterUtil.java [hunk 5]
```diff
@@ -108,34 +109,53 @@ public Boolean registerAtsign(String email, AtSign atsign, String registrarUrl,
      * @throws IOException
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: Please add documentation explaining use of the new 'confirmation' parameter (which should be optional as mentioned in next comment)

File: at_client/src/main/java/org/atsign/config/ConfigReader.java [hunk 6]
```diff
@@ -13,13 +13,15 @@
  * Loads, reads and returns properties from the configuration file in the resources
  */
 public class ConfigReader {
-    private Map<String, String> config;
+    private Map<String, Map<String, String>> config;
+    private Map<String,String>propertyMap;
 
-    public String getProperty(String property) throws StreamReadException, DatabindException, FileNotFoundException{
+    public String getProperty(String property, String subProperty) throws StreamReadException, DatabindException, FileNotFoundException{
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/config/ConfigReader.java:19]: Please preserve the getProperty(String property) for backwards compatibility and either add a new method, getNestedProperty(String property, String subProperty) or getNestedProperty(List<String> propertyNames) or similar

File: at_client/src/main/resources/config.yaml [hunk 7]
```diff
@@ -1,4 +1,7 @@
...
-ROOT_PORT: "64" 
-REGISTRAR_URL: "https://my.atsign.wtf/api/app/v2" ##staging registrar url. please use "https://my.atsign.com/api/app/v2" to use the production registrar api
\ No newline at end of file
+rootServer:
+  domain: "root.atsign.wtf" ##staging root server. use "root.atsign.org" to use the production root domain
+  port: "64"
+
+registrar:
+  url: "https://my.atsign.wtf/api/app/v2" ##staging registrar url. please use "https://my.atsign.com/api/app/v2" to use the production registrar api
+  apiKey: "477b-876u-bcez-c42z-6a3d" ##staging api key. please obtain a key to the production registrar api and replace it
```
Comment (gkc) [inline at_client/src/main/resources/config.yaml]: Please re-add the original config names, specifying in comments that they are there for backwards compatibility and that users should use, for example, rootServer:domain rather than ROOT_DOMAIN as ROOT_DOMAIN will be deprecated in future

**Review by gkc — CHANGES_REQUESTED** [review]

**Comment by srieteja** [comment]
latest commit addresses all review comments. Although I'm stuck with an issue where API sends an ArrayList of atsigns and I cannot cast into string or any other format.

File: at_client/src/main/java/org/atsign/client/util/RegisterUtil.java [hunk 8]
```diff
@@ -100,42 +109,86 @@ public Boolean registerAtsign(String email, AtSign atsign, String registrarUrl,
...
+     * @throws AtException Case 1: If user has exhausted 10 free atsign quota
+     *                     Case 2: If API response is anything other than
+     *                     HTTP_OK/Status_200.
      */
-    public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey)
+    public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey,
+            boolean ... confirmation)
             throws IOException, AtException {
+        //setting default confirmation to true in case it's not provided
+        Boolean defaultConfirmation = (confirmation.length == 0) ? true : confirmation[0];
```
Comment (gkc) [inline at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: This is not what I was looking for. I asked for the confirmation parameter to be made optional, I was thinking as a named optional parameter e.g. 
`public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey, {boolean confirmation = true})`

**Review by gkc — CHANGES_REQUESTED** [review]

File: at_client/src/main/java/org/atsign/client/util/RegisterUtil.java (hunk 8 above)
Comment (gkc) [reply at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: OMG I'm thinking of Dart

Comment (srieteja) [reply at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: yes, as far as StackOverflow goes this is one of the limited ways we can do optional parameters

Comment (gkc) [reply at_client/src/main/java/org/atsign/client/util/RegisterUtil.java]: Ignore my previous comments

To preserve backwards compatibility
1. Add new method `public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey, boolean confirmation)`
2. Keep existing method `public String validateOtp(String email, AtSign atsign, String otp, String registrarUrl, String apiKey)` with implementation `{validateOtp(email, atsign, otp, registrarUrl, apiKey, true); }` assuming that the default value for 'confirmation' is true

**Comment by gkc** [comment]
@srieteja 
> Although I'm stuck with an issue where API sends an ArrayList of atsigns and I cannot cast into string or any other format.

Can you explain more how you're stuck?

**Comment by srieteja** [comment]
The API responds with different formats for different requests. I have been able to handle using two collection types Map<String, String> and Map<String, Map<String, String>>. But for the added case now the API responds with an ArrayLIst as one of the parameters instead of String. If I try to print that ArrayList through sysout I'm getting a run-time error that says ArrayList cannot be casted to String and if I try to extract that into a variable of type ArrayList so that I can handle I'm getting a compile-time error that won't allow me to assign the list from API response to the variable as I have specified the type as Map<String, String>. I have tried to use Dynamic instead of String that has been giving me an error too for some apparent reason.

**Comment by gkc** [comment]
> The API responds with different formats for different requests. I have been able to handle using two collection types Map<String, String> and Map<String, Map<String, String>>. But for the added case now the API responds with an ArrayLIst as one of the parameters instead of String. If I try to print that ArrayList through sysout I'm getting a run-time error that says ArrayList cannot be casted to String and if I try to extract that into a variable of type ArrayList so that I can handle I'm getting a compile-time error that won't allow me to assign the list from API response to the variable as I have specified the type as Map<String, String>. I have tried to use Dynamic instead of String that has been giving me an error too for some apparent reason.

Please explain in the code, with commented code if necessary, so I can checkout the branch, understand better the problem, and propose a solution.

**Comment by srieteja** [comment]
[response.zip](https://github.com/atsign-foundation/at_java/files/8780395/response.zip)
In the above zip is the response json for the case I'm facing the error. In RegisterUtil.java line 175 I'm extracting the json value of field "data" to a Map<String, String>. Please try running the latest commit which most likely will throw an error due to newly added line 184(RegisterUtil.java)

**Comment by srieteja** [comment]
@gkc I was able to solve the thing I was stuck with. If the PR looks good to you we can go ahead and merge it.

**Review by gkc — APPROVED** [review]
LGTM
